apiVersion: apps/v1

kind: Deployment

metadata:

  name: flight-service

spec:

  replicas: 1

  selector:

    matchLabels:

      app: flight-service

  template:

    metadata:

      labels:

        app: flight-service

    spec:

      containers:

        - name: flight-service

          image: 713881799987.dkr.ecr.us-east-1.amazonaws.com/flight-service:v2

          ports:

            - containerPort: 8080

---

apiVersion: v1

kind: Service

metadata:

  name: flight-service

spec:

  type: LoadBalancer

  selector:

    app: flight-service

  ports:

    - protocol: TCP

      port: 80

      targetPort: 8080